# Generated by Django 3.1.12 on 2022-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('contact', models.JSONField()),
                ('address', models.TextField()),
            ],
        ),
    ]
