# Generated by Django 3.1.12 on 2022-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220405_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.TextField(null=True),
        ),
    ]
