# Generated by Django 3.1.12 on 2022-04-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220405_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hospital')),
            ],
        ),
    ]
