# Generated by Django 3.1.12 on 2022-04-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_hospitalfacilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalfacilities',
            name='img',
        ),
        migrations.CreateModel(
            name='FacilityImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hospitalfacilities')),
            ],
        ),
    ]
